// Product Database (Single Source of Truth)
const productsData = [
    {
        id: 1,
        name: "Basmati Rice Premium",
        category: "grains",
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800",
        origin: "India",
        packaging: "25kg, 50kg bags",
        moq: "1000 kg",
        price: 2.50,
        description: "Premium aged Basmati rice with extra-long grains and aromatic fragrance. Our Basmati rice is carefully sourced from the finest farms in India, aged to perfection for superior texture and taste. Ideal for biryanis, pulaos, and everyday meals. Each grain is meticulously selected to ensure consistent quality and authentic aroma.",
    },
    {
        id: 2,
        name: "Jasmine Rice",
        category: "grains",
        image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=800",
        origin: "Thailand",
        packaging: "25kg, 50kg bags",
        moq: "1000 kg",
        price: 2.30,
        description: "Fragrant Thai jasmine rice, perfect for Asian cuisine. Known for its soft texture and subtle floral aroma, this premium grade jasmine rice is ideal for restaurants and food service providers.",
    },
    {
        id: 3,
        name: "Tender Coconuts",
        category: "produce",
        image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800",
        origin: "India, Sri Lanka",
        packaging: "Per piece, bulk crates",
        moq: "500 pieces",
        price: 1.20,
        description: "Fresh tender coconuts, rich in natural electrolytes. Harvested at peak freshness and delivered with care. Perfect for direct consumption or coconut water extraction.",
    },
    {
        id: 4,
        name: "Premium Cashews",
        category: "nuts",
        image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800",
        origin: "Vietnam, India",
        packaging: "10kg, 25kg cartons",
        moq: "100 kg",
        price: 12.50,
        description: "Grade A whole cashews, naturally processed. Carefully selected and quality-checked for uniform size and color. Perfect for snacking, cooking, or processing.",
    },
    {
        id: 5,
        name: "California Almonds",
        category: "nuts",
        image: "https://images.unsplash.com/photo-1508747703725-719777637510?w=800",
        origin: "USA",
        packaging: "10kg, 25kg bags",
        moq: "100 kg",
        price: 15.00,
        description: "Premium California almonds, rich in nutrients. Non-GMO verified, packed with protein, fiber, and healthy fats. Available in raw or roasted varieties.",
    },
    {
        id: 6,
        name: "Black Pepper Whole",
        category: "spices",
        image: "https://images.unsplash.com/photo-1596040033229-a0b3b83cbf1c?w=800",
        origin: "Vietnam, India",
        packaging: "25kg bags",
        moq: "500 kg",
        price: 8.50,
        description: "Bold and aromatic whole black peppercorns. Premium quality with high piperine content for maximum flavor. Ideal for spice blending and food manufacturing.",
    },
    {
        id: 7,
        name: "Green Cardamom",
        category: "spices",
        image: "https://images.unsplash.com/photo-1598016815563-36f0bb7c65c7?w=800",
        origin: "India, Guatemala",
        packaging: "5kg, 10kg cartons",
        moq: "50 kg",
        price: 45.00,
        description: "Premium green cardamom pods with intense aroma. Hand-picked and carefully dried to preserve essential oils. Perfect for both sweet and savory applications.",
    },
    {
        id: 8,
        name: "Dried Mango Slices",
        category: "processed",
        image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=800",
        origin: "Philippines, India",
        packaging: "5kg, 10kg bags",
        moq: "100 kg",
        price: 6.00,
        description: "Naturally dried mango slices, no added sugar. Made from premium mango varieties, sun-dried or low-temperature processed to retain natural sweetness and nutrients.",
    },
    {
        id: 9,
        name: "Frozen Mixed Vegetables",
        category: "frozen",
        image: "https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?w=800",
        origin: "India, China",
        packaging: "1kg, 2.5kg bags",
        moq: "500 kg",
        price: 3.20,
        description: "IQF (Individually Quick Frozen) mixed vegetables, preserving freshness and nutrients. Perfect blend for restaurants, catering, and food processing.",
    },
    {
        id: 10,
        name: "Walnuts (Kernels)",
        category: "nuts",
        image: "https://images.unsplash.com/photo-1622495694065-d54a2aef9b6f?w=800",
        origin: "Chile, USA",
        packaging: "10kg cartons",
        moq: "100 kg",
        price: 18.00,
        description: "Premium walnut kernels, light halves. High in omega-3 fatty acids and antioxidants. Carefully shelled and sorted for consistent quality.",
    },
    {
        id: 11,
        name: "Cinnamon Sticks",
        category: "spices",
        image: "https://images.unsplash.com/photo-1599909533730-f9c6e9c3f5d5?w=800",
        origin: "Sri Lanka",
        packaging: "10kg, 25kg bags",
        moq: "200 kg",
        price: 22.00,
        description: "Ceylon cinnamon sticks, premium grade. Known for its delicate sweet flavor and thin, paper-like bark. Superior to cassia cinnamon in aroma and health benefits.",
    },
    {
        id: 12,
        name: "Organic Quinoa",
        category: "grains",
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800",
        origin: "Peru, Bolivia",
        packaging: "25kg bags",
        moq: "500 kg",
        price: 5.50,
        description: "Certified organic quinoa, high in protein. Complete plant-based protein source with all nine essential amino acids. USDA Organic and Fair Trade certified.",
    }
];